KusionStack/kuperator

- releaser.Dockerfile
> fix: update releaser

- apis/apps/v1alpha1/collaset_types.go
- config/crd/bases/apps.kusionstack.io_collasets.yaml
> chore(CollaSet): correct comment

- pkg/controllers/resourceconsist/resourceconsist_controller_test.go
> fix: resource consist ut, get svc just after creation might return 404

- .goreleaser.yaml
.goreleaser.yaml
```release-note
None
```
> Enhancement: support linux/arm64 image release

- .github/workflows/ci.yaml
- README.md
> docs: enrich the readme badges

- config/crd/kustomization.yaml
> add poddecoration in kustumizations

- pkg/controllers/collaset/collaset_controller.go
- pkg/controllers/collaset/revision.go
- pkg/controllers/utils/revision/revision_manager.go
> fix collaset revision panic: issue#148

- apis/apps/v1alpha1/collaset_types.go
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- pkg/webhook/server/generic/collaset/collaset_validating_handler.go
- pkg/webhook/server/generic/collaset/collaset_validating_handler_test.go
> refactor: update the PodUpdateStrategyType from ReplaceUpdate to Replace

- pkg/webhook/server/generic/pod/gracedelete/webhook.go
- pkg/webhook/server/generic/pod/gracedelete/webhook_test.go
> adjust grace delete webhook message

- apis/apps/v1alpha1/collaset_types.go
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/webhook/server/generic/collaset/collaset_validating_handler_test.go
> refactor: correct ReCreate to Recreate

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> fix: pin go version in release workflows and disable secret scan

- .github/workflows/ci.yaml
- .licenserc.yaml
- charts/Chart.yaml
- charts/templates/NOTES.txt
- charts/templates/crd/apps.kusionstack.io_collasets.yaml
- charts/templates/crd/apps.kusionstack.io_poddecorations.yaml
- charts/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- charts/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- charts/templates/namespace.yaml
- charts/templates/rbac/rbac.yaml
- charts/templates/service.yaml
- charts/templates/shardingconfig.yaml
- charts/templates/statefulset.yaml
- charts/templates/webhook/webhook.yaml
- charts/values.yaml
- config/webhook/webhook.yaml
Add the charts directory to maintain the latest kube resources.
> enhance: add charts and support webhook dry run after v0.3.0

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
- pkg/webhook/server/generic/pod/opslifecycle/validating.go
- pkg/webhook/server/generic/pod/pod_mutating_handler.go
> fix: no blocking when delete po

- pkg/controllers/collaset/collaset_controller_test.go
> fix PVC UT: use Eventually instead of time.sleep

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/podcontext/podcontext.go
fix #184 
```release-note
None
```
> fix(CollaSet): clean up PodContext if it is empty

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
- pkg/webhook/server/generic/pod/opslifecycle/webhook_test.go
re https://github.com/KusionStack/operating/issues/214
```release-note
None
```
> fix: remove unuseful labels

- README.md
> update tutorial url

- apis/apps/v1alpha1/collaset_types.go
- config/crd/bases/apps.kusionstack.io_collasets.yaml
> rephrase collaset api partition

- Makefile
- charts/Chart.yaml
- charts/templates/NOTES.txt
- charts/templates/crd/apps.kusionstack.io_collasets.yaml
- charts/values.yaml
> feat: update chart version to v0.5.0

- pkg/controllers/utils/poddecoration/strategy/manager.go
> chore: delete unused code

- .github/workflows/ci.yaml
- .licenserc.yaml
- apis/apps/v1alpha1/defaults.go
- apis/apps/v1alpha1/podtransitionrule_types.go
- apis/apps/v1alpha1/well_known_labels.go
- charts/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- config/crd/bases/apps.kusionstack.io_podtransitionrules.yaml
- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/collaset/utils/pod.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- pkg/controllers/podtransitionrule/processor/rules/webhook.go
- pkg/controllers/utils/expectations/active_expectation.go
- pkg/controllers/utils/poddecoration/patch/container.go
- pkg/utils/common.go
- pkg/utils/pki_helpers.go
- pkg/webhook/server/generic/collaset/collaset_mutating_handler.go
- pkg/webhook/server/generic/collaset/collaset_mutating_handler_test.go
- pkg/webhook/server/generic/collaset/collaset_validating_handler_test.go
- test/e2e/framework/test_context.go
- test/e2e/framework/util.go
- typos.toml
Add crate-ci/typos to find and correct spelling mistakes among source code.
> chore: add code spell checker

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/replace.go
- pkg/controllers/poddeletion/poddeletion_controller.go
- test/e2e/apps/collaset.go
- test/e2e/framework/collaset_util.go
> CollaSet support cancel replace pod

- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/poddecoration/poddecoration_controller.go
- pkg/controllers/poddecoration/poddecoration_controller_test.go
- pkg/controllers/utils/poddecoration/anno/anno.go
- pkg/controllers/utils/poddecoration/getter.go
- pkg/controllers/utils/poddecoration/getter_test.go
- pkg/controllers/utils/poddecoration/patch.go
- pkg/controllers/utils/poddecoration/patch_test.go
- pkg/controllers/utils/poddecoration/strategy/manager.go
- pkg/controllers/utils/poddecoration/strategy/types.go
- pkg/controllers/utils/poddecoration/strategy/utils.go
PodDecoration
```release-note
None
```
> echance poddecoration partition sort rule

- pkg/controllers/poddeletion/poddeletion_controller_test.go
- pkg/controllers/poddeletion/predict.go
> poddeletion-controller watch collaset pod

- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/handler.go
- pkg/controllers/operationjob/replace/replace.go
> add recorder to operationjob action handler funcs

- pkg/controllers/operationjob/operationjob_controller.go
- pkg/controllers/operationjob/operationjob_controller_test.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/replace/replace.go
- test/e2e/apps/operationjob.go
> improve replace: add finalizer for origin pod, improve list new pod, add some events

- charts/templates/crd/apps.kusionstack.io_operationjobs.yaml
- config/crd/bases/apps.kusionstack.io_operationjobs.yaml
- go.mod
- go.sum
- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
> PodStayTrafficOffLabel: stay in traffic off phase

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- [] N
re https://github.com/KusionStack/operating/issues/248
```release-note
None
```
> fix: readiness-gate with concurrency

- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
> clean all id's labels when undo operation

- apis/apps/v1alpha1/defaults.go
- pkg/webhook/server/generic/poddecoration/poddecoration_validating_handler.go
> validate default volumes

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
> fix: set readiness gate in order

- pkg/controllers/collaset/synccontrol/update.go
- test/e2e/apps/collaset.go
> fix-inplace-with-2-or-more-containers

- apis/apps/v1alpha1/helper.go
- charts/templates/crd/apps.kusionstack.io_operationjobs.yaml
- config/crd/bases/apps.kusionstack.io_operationjobs.yaml
- go.mod
- go.sum
- pkg/controllers/operationjob/operationjob_controller.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/candidate.go
- pkg/controllers/operationjob/opscore/handler.go
- pkg/controllers/operationjob/opscore/lifecycle.go
- pkg/controllers/operationjob/replace/replace.go
- pkg/controllers/operationjob/utils/common.go
- pkg/controllers/operationjob/utils/lifecycle.go
- test/e2e/apps/operationjob.go
> refactor opsStatus

- pkg/controllers/poddecoration/poddecoration_controller.go
> pd only reconcile active pods

- pkg/controllers/utils/poddecoration/patch/volume.go
> Fix: abnormal  sequence issue with volume

- pkg/controllers/collaset/synccontrol/replace.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- test/e2e/apps/collaset.go
> Fix collaset pd update separate

- pkg/controllers/utils/poddecoration/anno/anno.go
- pkg/controllers/utils/poddecoration/patch.go
- pkg/controllers/utils/poddecoration/patch_test.go
> add pd ownerRef on pod

- pkg/controllers/operationjob/operationjob_controller_test.go
- pkg/controllers/operationjob/replace/event_handler.go
- pkg/controllers/operationjob/replace/replace.go
> Fix opj replace succeeded unexpected

- pkg/webhook/server/generic/collaset/collaset_mutating_handler.go
- pkg/webhook/server/generic/collaset/collaset_mutating_handler_test.go
- pkg/webhook/server/generic/collaset/collaset_validating_handler.go
> move collaset setPodSpec in validating

- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/utils/condition.go
> fix scaleOutFailed condition not show

- config/manager/kustomization.yaml
- pkg/controllers/collaset/collaset_controller.go
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/replace.go
- pkg/controllers/collaset/synccontrol/scale.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/utils/podopslifecycle/utils.go
- pkg/webhook/server/generic/pod/gracedelete/webhook_test.go
- test/e2e/apps/collaset.go
> Fix replace with delete or scaleIn

- pkg/controllers/utils/poddecoration/strategy/manager.go
> fix: not found collaset issue in pd manager

- charts/Chart.yaml
- charts/values.yaml
> feat: update charts version to v0.6.0

- pkg/controllers/collaset/collaset_controller.go
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/poddecoration/poddecoration_controller.go
> remove pd ownerReferece from pod when cls delete

- README.md
> add operationjob intro in readme

- pkg/controllers/operationjob/operationjob_controller_test.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/candidate.go
> make candidates order stable

- pkg/controllers/collaset/collaset_controller.go
> fix condition always update

- pkg/controllers/collaset/collaset_controller_test.go
> remove image utils pkg from ut

- go.mod
- go.sum
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
> Add pod labels to indicate PodOpsLifecycle phase

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
> fix podopslifecycle set readiness gate order

- pkg/controllers/operationjob/operationjob_manager.go
> bugfix: stop doing ttl when endtime is nil

- pkg/controllers/podtransitionrule/podtransitionrule_controller.go
to ensure pod detail update envents is after ptr update events.
> ptr: update pod detail after ptr status sync

- pkg/controllers/podtransitionrule/eventhandler.go
Fix issues introduced by PR https://github.com/KusionStack/kuperator/pull/306
> fix: ptr lost events case

- config/manager/kustomization.yaml
- pkg/controllers/collaset/podcontext/podcontext.go
- pkg/webhook/server/generic/generic_webhooks.go
- pkg/webhook/server/generic/resourcecontext/resourcecontext_mutating_handler.go
- pkg/webhook/server/generic/resourcecontext/resourcecontext_validating_handler.go
- test/e2e/apps/collaset.go
> add resourrcecontext webhook and improve logic

- pkg/controllers/collaset/synccontrol/replace.go
> show replace failed message

- pkg/controllers/collaset/synccontrol/sync_control.go
> fix: update scaleOut condition when diff=0

- pkg/controllers/collaset/synccontrol/update.go
> fix: use spec.replicas instead of pod num to decide pod to update

- pkg/controllers/collaset/collaset_controller.go
- pkg/controllers/collaset/synccontrol/sync_control.go
> feat: terminating pods when collaset is deleted

- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/utils/poddecoration/strategy/types.go
> fix: service unavailable pod should take priority over available when updating

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- pkg/controllers/collaset/collaset_controller.go
> fix: update observedGeneration when sync failed

- config/manager/kustomization.yaml
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/scale.go
- pkg/controllers/collaset/synccontrol/sync_control.go
> fix: scale in stuck bug when scaleIn  is cancelled

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> ci: bump up ubuntu/checkout/setup version in github workflow

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/replace.go
- pkg/controllers/collaset/synccontrol/update.go
> fix: replace update v1 to v3 with endless reconciling

- pkg/controllers/collaset/collaset_controller.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/utils/condition.go
> fix: don't update ScaleIn condition in empty reconcile

- pkg/controllers/collaset/synccontrol/replace.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/poddeletion/poddeletion_controller.go
> refact: add some logs for collaset reconcile

- charts/Chart.yaml
- charts/values.yaml
> upgrade charts 0.6.4
