- pkg/controllers/utils/expectations/active_expectation.go
- pkg/controllers/utils/expectations/active_expectation_test.go
- pkg/controllers/utils/expectations/expectation.go
- pkg/controllers/utils/expectations/expectations_suite_test.go
- pkg/controllers/utils/expectations/resourceversion_expectation.go
- pkg/controllers/utils/expectations/resourceversion_expectation_test.go
re https://github.com/KusionStack/operating/issues/20
```release-note
None
```
> add unit test for ResourceVersionExpectation

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/utils/pod_utils.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
re #119 
```release-note
None
```
> feat: add compensation logic in service-available calculation

- docs/proposals/20231012-pod-decoration.md
PodDecoration Proposal
```release-note
None
```
> feat: update PodDecoration API design

- pkg/controllers/podtransitionrule/processor/rules/webhook.go
pkg/controllers/podtransitionrule/processor/rules/webhook.go
```release-note
None
```
> fix: podTransitionRule webhook

- go.mod
- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- pkg/controllers/podopslifecycle/predicate.go
- pkg/controllers/podopslifecycle/utils_test.go
- pkg/controllers/utils/pod_utils.go
re https://github.com/KusionStack/operating/issues/137
```release-note
None
```
> optimize ut in podopslifecycle controller

- pkg/controllers/collaset/synccontrol/update.go
> fix issue #135: update all pod if partition > replicas

- pkg/webhook/server/generic/pod/gracedelete/webhook.go
- pkg/webhook/server/generic/pod/gracedelete/webhook_test.go
pkg/webhook/server/generic/pod/gracedelete
Limit the effective scope of gracedelete webhook, considering the pod without service-ready ReadinessGate.
```release-note
None
```
> fix: gracedelete webhook compatible in the absence of ServiceReadyReadinessGate

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/scale.go
> getPodsToDelete(): delete the pods in ScaleInOpsLifecycleAdapter first

- apis/apps/v1alpha1/well_known_labels.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/collaset/utils/lifecycle_adapter.go
- pkg/controllers/poddeletion/lifecycle_adapter.go
- pkg/controllers/utils/podopslifecycle/adapter.go
- pkg/controllers/utils/podopslifecycle/delete.go
- pkg/controllers/utils/podopslifecycle/utils.go
collaset controller
```release-note
None
```
> Support label the pods that need to be deleted before the preparing phase

- Makefile
Test fails because of recent bug https://github.com/kubernetes-sigs/controller-runtime/issues/2720
```release-note
None
```
> fix: stable setup-envtest version

- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- pkg/controllers/utils/pod_utils.go
- pkg/controllers/utils/pod_utils_test.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
- pkg/webhook/server/generic/pod/opslifecycle/validating.go
- pkg/webhook/server/generic/pod/opslifecycle/webhook.go
- pkg/webhook/server/generic/pod/opslifecycle/webhook_test.go
fix https://github.com/KusionStack/operating/issues/170
```release-note
None
```
> fix: podopslifecycle webhook waits for more events

- apis/apps/v1alpha1/well_known_vars.go
- pkg/controllers/poddeletion/lifecycle_adapter.go
- pkg/controllers/poddeletion/poddeletion_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
re https://github.com/KusionStack/operating/issues/172
```release-note
None
```
> refactor: optimize the events about pods

- apis/apps/v1alpha1/collaset_types.go
- apis/apps/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/apps.kusionstack.io_collasets.yaml
- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/scale.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/utils/pod.go
- pkg/features/features.go
- pkg/webhook/server/generic/collaset/collaset_mutating_handler.go
> Scale strategy pod to delete

- .gitignore
- charts/Chart.yaml
- charts/templates/NOTES.txt
- charts/templates/crd/apps.kusionstack.io_collasets.yaml
- charts/templates/crd/apps.kusionstack.io_poddecorations.yaml
- charts/values.yaml
> feat: update charts version to v0.4.0

- pkg/controllers/utils/podopslifecycle/utils.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
- pkg/webhook/server/generic/pod/opslifecycle/validating.go
- pkg/webhook/server/generic/pod/opslifecycle/webhook.go
- pkg/webhook/server/generic/pod/opslifecycle/webhook_test.go
> delete operation-type when all IDs' operate finished

- apis/apps/v1alpha1/poddecoration_types.go
- charts/templates/crd/apps.kusionstack.io_poddecorations.yaml
- config/crd/bases/apps.kusionstack.io_poddecorations.yaml
- pkg/controllers/poddecoration/poddecoration_controller.go
- pkg/controllers/utils/poddecoration/getter.go
PodDecoration
Fix:
1. Delay clear pd finalizer: delete finalizer after all pods escape to ensure cls get old pd controllerrevision.
2. Delete poddecoration 'EFFECTIVE' printcolumn 
```release-note
None
```
> Fix: delay clear pd finalizer and delete invalid printcolumn 

- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- test/e2e/apps/collaset.go
> Refactor inplaceOnlyPodUpdater plugin

- pkg/controllers/operationjob/operationjob_manager.go
> update opj status in releaseTargets

- pkg/controllers/podopslifecycle/podopslifecycle_controller.go
- pkg/controllers/podopslifecycle/podopslifecycle_controller_test.go
- pkg/controllers/podopslifecycle/utils.go
- pkg/controllers/podopslifecycle/utils_test.go
- pkg/webhook/server/generic/pod/opslifecycle/mutating.go
fix https://github.com/KusionStack/kuperator/issues/283
```release-note
None
```
> fix: remove label service-available when pod is not ready

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/sync_control.go
> fix pod create failed with pd

- go.mod
- go.sum
- pkg/controllers/operationjob/operationjob_controller.go
- pkg/controllers/operationjob/operationjob_controller_test.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/candidate.go
- pkg/controllers/operationjob/opscore/handler.go
- pkg/controllers/operationjob/replace/replace.go
- pkg/controllers/operationjob/utils/common.go
> operate targets in batch

- charts/templates/crd/apps.kusionstack.io_operationjobs.yaml
- config/crd/bases/apps.kusionstack.io_operationjobs.yaml
- go.mod
- go.sum
- pkg/controllers/operationjob/operationjob_controller.go
- pkg/controllers/operationjob/operationjob_controller_test.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/candidate.go
- pkg/controllers/operationjob/utils/common.go
> refactor activeDeadlineSeconds to target-level

- pkg/controllers/collaset/synccontrol/update.go
- test/e2e/apps/collaset.go
> bugfix: operationDelaySeconds for update endless reconcile

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/collaset/synccontrol/sync_control.go
- pkg/controllers/collaset/synccontrol/update.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/utils/lifecycle.go
- pkg/controllers/podopslifecycle/utils.go
- pkg/controllers/utils/podopslifecycle/utils.go
- test/e2e/apps/collaset.go
> feat: support clean old lifecycle before new update

- pkg/controllers/utils/poddecoration/getter.go
```
concurrent map writes
I1127 11:41:34.103024       1 sync_control.go:406] collaset-controller "msg"="try to create Pod with revision of collaSet" "collaset"="e2e-tests-collaset-75392/collaset-2lrv67mrtc-inplaceifpossible" "revision"="collaset-2lrv67mrtc-inplaceifpossible-d4bb4649c"
goroutine 7004 [running]:
kusionstack.io/kuperator/pkg/controllers/utils/poddecoration.(*namespacedPodDecorationManager).getByRevision(0xc000a72ae0, {0x1c01498, 0xc00051bbc0}, {0xc000cbb1a0, 0x2a})
/workspace/pkg/controllers/utils/poddecoration/getter.go:163 +0x219
kusionstack.io/kuperator/pkg/controllers/utils/poddecoration.(*namespacedPodDecorationManager).GetByRevisions(0xc000a72ae0, {0x1c01498, 0xc00051bbc0}, {0xc000914070, 0x1, 0x289c360?})
/workspace/pkg/controllers/utils/poddecoration/getter.go:96 …
```
> fix poddecoration concurrent map writes

- pkg/controllers/operationjob/operationjob_controller.go
- pkg/controllers/operationjob/operationjob_manager.go
- pkg/controllers/operationjob/opscore/candidate.go
- pkg/controllers/operationjob/opscore/handler.go
- pkg/controllers/operationjob/replace/replace.go
- pkg/controllers/operationjob/utils/common.go
> Improve opj handler returned errors

- pkg/controllers/collaset/collaset_controller_test.go
- pkg/controllers/operationjob/operationjob_manager.go
- test/e2e/apps/collaset.go
> fix: opj should failed if ops not found pod

- pkg/controllers/collaset/synccontrol/scale.go
- test/e2e/apps/collaset.go
> bugfix: selective scale in both new and origin pods

- go.mod
- go.sum
- pkg/controllers/collaset/pvccontrol/pvc_control.go
- pkg/controllers/collaset/synccontrol/scale.go
- pkg/controllers/collaset/utils/pvc.go
- test/e2e/apps/collaset.go
- test/e2e/framework/collaset_util.go
> improve extract pvc template name from pvc
